### ISSUE TITLE
Termine am selben Tag nur für Moderatoren sichtbar

### ISSUE THREAD

**Issue by mathiasbc1** [drkTettnang/corona-testing#10]
Guten Morgen!

Kurze Frage zur Bedienung der Applikation.
Mir fällt auf, dass auf der öffentlichen Seite keine Termine für den aktuellen Tag sichtbar sind.
Auch bei Registrierung fehlt der heutige Tag. Ich kann frühestens für den darauffolgenden Tag buchen.
Melde ich mich als Moderator an, kann ich allerdings einen Termin für den aktuellen Tag buchen.
Wo lässt sich das steuern?

Ansicht als reg. User:
![image](https://user-images.githubusercontent.com/58967389/144557758-dfc59bcb-25c9-4887-8dad-a5a00ed1005f.png)

und hier die Sicht als Moderator:
![image](https://user-images.githubusercontent.com/58967389/144557966-a76ba80e-ba8c-4866-b8a5-f1aeac11ba36.png)

Weitere Frage:
QR-Codes für die Corona-Warn-App: Lassen sich Codes generieren, die per CW-App eingescannt werden können?

Danke und Grüße
Mathias

**Comment by sualko** [comment]
> Wo lässt sich das steuern?

In den Einstellungen der Örtlichkeit. Das Problem ist, wenn man kurzfristige Anmeldungen erlaubt muss man auch fortlaufend die Einverständniserklärungen drucken. Daher ist der Standard das man sich bis zum Tag davor anmelden muss, damit man vor der Testung alle Anmeldungen drucken kann. Wenn man kurzfristige Anmeldungen erlaubt, braucht man einen PC mit Drucker bei dem man die Seite `/print` öffnet um neue Anmeldungen zu drucken. Siehe hierzu auch den letzten Punkt im [Troubleshooting](https://github.com/drkTettnang/corona-testing#pick-troubleshooting).

![image](https://user-images.githubusercontent.com/2974196/144597743-a3fbc8d7-fc40-4c5c-9eb5-98323f2cd3b2.png)

> Lassen sich Codes generieren, die per CW-App eingescannt werden können?

Wenn alle Einstellungen im `.env` für die CWA konfiguriert worden, erscheint der QR-Code auf den Einverständniserklärungen. Zusätzlich erhält man einen Link in der Ergebnis-Mail.
