### ISSUE TITLE
Zertifikate und CWA-Anbindung

### ISSUE THREAD

**Issue by mathiasbc1** [drkTettnang/corona-testing#11]
Guten Abend,

endlich habe ich das Zertifikat gegensigniert bekommen und stehe nun vor der Herausforderung das einzubinden.
Für den Test (WRU) habe ich diese Files generiert:
![image](https://user-images.githubusercontent.com/58967389/159778220-84717565-6872-4b85-bf7f-0114646ec825.png)

T-Systems hat folgendes Zertifikat zurückgesendet:
![image](https://user-images.githubusercontent.com/58967389/159778562-9018cd11-9a1d-4a20-8996-d87e8c77b052.png)

Nun bräuchte ich bitte noch Hilfe, wie ich die Zertifikate in der .env einbinde, bzw. wo welches hingehört.
![image](https://user-images.githubusercontent.com/58967389/159778938-bd1856a4-cc40-496b-9b77-ca1b107aeb92.png)

Bei "CWA_CLIENT_PASSPHRASE" muss vermutlich das beim Generieren hinterlegte Kennwort rein, beim Rest weiß ich leider nicht, wie ich die Dateien hinterlegen soll.

Ich freue mich über eure Hilfe.

Danke und viele Grüße ;)

**Comment by sualko** [comment]
> Bei "CWA_CLIENT_PASSPHRASE" muss vermutlich das beim Generieren hinterlegte Kennwort rein

Korrekt. Ansonsten fehlt das `https://` bei `CWA_SERVER`. Bei `CWA_CLIENT_CRT` gehört das `.cer` file hin und nicht der signing request. `CWA_CLIENT_CA` kann in diesem Fall leer bleiben. Alle Pfade sollten absolute sein (z.B. `/etc/cwa-oder-sonst-was/`) und vorallem nicht im public Order, da sonst jeder drauf zugreifen kann!
