### ISSUE TITLE
Problem beim Deploy der Datenbank

### ISSUE THREAD

**Issue by mathiasbc1** [drkTettnang/corona-testing#9]
Guten Morgen,

ich verwende als Betriebssystem CentOS 8.5. Die mysql Datenbank habe ich nach Vorgabe für CentOS installiert.
Leider komme ich an der Stelle nicht weiter: yarn deploy:db wirft folgenden Fehler:

Error: Schema Parsing P1012

Get config
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:6
   |
 5 |   provider = "mysql"
 6 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1

Wenn jemand eine gute Idee hat, würde ich mich freuen :)

Viele Grüße und vorab herzlichen Dank!

**Comment by sualko** [comment]
Hast du eine `.env` Datei mit den entsprechenden Werten? Siehe dazu den ersten Satz der [Installationsanleitung](https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html).

Viele Grüße, 
Klaus

**Comment by mathiasbc1** [comment]
Hallo Klaus,

vielen Dank für deine Antwort. Führt die Installationsanleitung ggf. zum falschen Ziel?
Hier finde ich nichts über eine .env Datei. Ich möchte die Corona-Testing-App installieren.

Zu deiner Frage:
Ich habe den gesamten Inhalt des Projekts heruntergeladen, und die .env-example angepasst und mit meinen Daten gefüllt
![image](https://user-images.githubusercontent.com/58967389/144034414-e09ea6fd-dfa8-4202-b778-5f6128a01ba7.png)

Ich würde also sagen ja.

Grüße
Mathias

**Comment by sualko** [comment]
Link sollte natürlich zum Readme führen.

> und die .env-example angepasst und mit meinen Daten gefüllt

Der Dateigröße der `.env` Datei nach hast du nicht die `.env-example` angepasst, sondern sie zuerst kopiert und umbenannt in `.env`. Das sollte also passen. Warum die Datei nicht gelesen wird, kann ich nicht sagen, aber jemand der CentOS nutzt, sollte das eigentlich raus bekommen :wink:. Da der Screenshot nach Windows aussieht, könnte es ein encoding / line ending Problem sein. Vielleicht findest du auch bei Prisma (db adapter) etwas Hilfe: 
https://www.prisma.io/docs/guides/development-environment/environment-variables

**Comment by mathiasbc1** [comment]
Guten Morgen Klaus,

vielen Dank für deine Rückmeldung. Ich konnte das Problem gestern umgehen, indem ich das "schema.prisma" im Anwendungsordner etwas "angepasst" habe:
![image](https://user-images.githubusercontent.com/58967389/144178951-45a584f9-1696-49d5-ae84-9890361f4b4e.png)

Läuft damit nun auch unter CentOS.
Gibt es eigentlich ein Handbuch zur Administration der Termine/ User, etc.?

Grüße
Mathias

**Comment by sualko** [comment]
> Ich konnte das Problem gestern umgehen, indem ich das "schema.prisma" im Anwendungsordner etwas "angepasst" habe

Schön das es funktioniert, aber ich würde nicht empfehlen den root user zu nutzen. Wenn die `.env` Datei nicht gelesen wird, wird es natürlich schwierig andere Sachen zu konfigurieren.

> Gibt es eigentlich ein Handbuch zur Administration der Termine/ User, etc.?

Dafür war leider bisher keine Zeit, aber Beiträge sind immer gerne gesehen. Bei Fragen, bitte melden.
